version: 2.1
orbs:
  cloudrun: circleci/gcp-cloud-run@1.0.2
jobs:
  build:
    docker:
      - image: circleci/node:12.13.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run build

  lint:
    docker:
      - image: circleci/node:12.13.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install --dev
      - run: npm run lint

  deploy:
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout
      - cloudrun/init
      - cloudrun/build:
          args: >
            --substitutions=_TAG=_PROJECT_ID=${GOOGLE_PROJECT_ID},
            _IMAGE_TAG=${CIRCLE_BUILD_NUM},
            _DATABASE_URL=${DATABASE_URL},
            _IMAGE_DEST=eu.gcr.io/${GOOGLE_PROJECT_ID}/frontend
      - cloudrun/deploy:
          image: "eu.gcr.io/${GOOGLE_PROJECT_ID}/frontend:${CIRCLE_BUILD_NUM}"
          platform: managed
          region: ${GOOGLE_COMPUTE_ZONE}
          service-name: frontend
          unauthenticated: true

workflows:
  build:
    jobs:
      - build
      - lint
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
