version: 2.1
orbs:
  cloudrun: circleci/gcp-cloud-run@1.0.2
jobs:
  build:
    docker:
      - image: circleci/node:12.13.0
    working_directory: ~/repo
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn build

  lint:
    docker:
      - image: circleci/node:12.13.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn lint

  deploy:
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout
      - cloudrun/init
      - cloudrun/build:
          tag: "eu.gcr.io/${GOOGLE_PROJECT_ID}/switch-${CIRCLE_SHA1}"
      - cloudrun/deploy:
          image: "eu.gcr.io/${GOOGLE_PROJECT_ID}/switch-${CIRCLE_SHA1}"
          platform: managed
          region: ${GOOGLE_COMPUTE_ZONE}
          service-name: frontend

workflows:
  build_and_deploy:
    jobs:
      - build
      - lint:
          requires:
            - build
      # TODO: deploy only from master
      - deploy:
          requires:
            - build
